config/routes.rb
Homerefs::Application.routes.draw do
  # get "errors/error_404"
  # get "errors/error_500"

  resources :feedbacks

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'public#landing'

  resources :reviews, :only => [:new, :show, :edit, :create, :update ]

  resources :apartments

  resources :buildings

  resources :users

  resources :identities

  match '/home', to: 'reviews#home'
  match '/about', to: 'public#about_us'
  match '/how-it-works', to: 'public#how_it_works'
  match '/faq', to: 'public#faq'
  match '/terms', to: 'public#terms'
  match '/contact', to: 'public#contact'
  match '/auth/:provider/callback', to: 'sessions#create'
  match "/auth/failure", to: "sessions#failure"
  match '/login', to: 'sessions#new', as: 'login'
  match '/logout', to: 'sessions#destroy', as: 'logout'
  match '/search', to: 'buildings#search'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/building.rb
class Building < ActiveRecord::Base

  include FieldAvgs
  define_field_avgs

  CONSTRUCTION = {1=>"Pre-War",2 => "Post-War", 3=>"New Construction"}
  DEFAULT_SORT = "score desc, reviews_count desc"
  belongs_to :neighborhood
  has_many :reviews
  has_many :reviewers,:through => :reviews, :source => :user
  validates :neighborhood, :presence => true
  validates :address, :presence => true
  validates :avg_rent, :numericality => true, allow_blank: true
  validates_format_of :zipcode,
    :with => %r{\d{5}(-\d{4})?},
    :message => "should be 12345 or 12345-1234", :if => "zipcode.present?"

  before_create :normalize
  has_many :building_images
  has_one :default_building_image, :class_name => "BuildingImage", :conditions => proc{["building_images.id = ?", default_image_id || building_images.first ]}
  paginates_per 10

   accepts_nested_attributes_for :building_images


  def self.highest_rated
    self.all.max_by(&:score)
  end

  def self.locate(params = {})

    building= where(:zipcode => params[:zipcode].strip) if params[:zipcode].present?
    building= where(:address => params[:address].strip) if params[:address].present?
    building= where(:neighborhood_id => params[:neighborhood].strip) if params[:neighborhood].present?
    building
  end

  def self.find_by_reviewer_average_rent(op, amt, type=nil)
    Building.all.select { |b| b.reviewer_avg_rent(type).send(op.to_sym, amt) }
  end

  def avg_rent= value
    return if value.blank?
    write_attribute("avg_rent", value)
    update_column(:reviewer_avg_rent, value)
  end

  def self.find_by_avg_rent(op, amt )
    Building.where("reviewer_avg_rent #{op} ?", amt)
  end

  def self.super_search(params)
    self.locate(params).search(params[:search])
  end

  def self.search(search)
    where(' upper(address) like ?', "%#{search.upcase}%")
  end

  def name
    address
  end

  def rent_range
    admin_rent_range || reviewer_rent_range
  end

  def reviewer_average_age
    if reviewers.count > 0
      cnt = reviewers.uniq.count
      (reviewers.uniq.map(&:age).inject{|sum,a|sum+a}.to_f/cnt).round
    else
      0
    end
  end

  def average_years_lived
    if reviews.count > 0
      cnt = reviews.uniq.count
      (reviews.uniq.map(&:years_lived).inject{|sum,a|sum+a}.to_f/cnt).round
    else
      0
    end
  end

  def apt_types
    types = {}
    reviews.each do |r|
      if !r.apt_size.nil?
        key = r.apt_size ==0 ? "Studio" : "#{r.apt_size} BR"
        types[key] = types[key].present? ? types[key]+1 : 1
      end
    end
    types
  end

  def flags_thrown
    flags = {}
    reviews.each do |r|
      key = Review::FLAGS[r.assessment]
      flags[key] = flags[key].present? ? flags[key]+1 : 1
    end
    flags
  end


  def construction
    CONSTRUCTION[construction_type]
  end

  def has_doorman
    doorman ? "Yes" : "No"
  end

  def has_elevator
    elevator ? "Yes" : "No"
  end

  def has_super
    self.super ? "Yes" : "No"
  end

  def is_coop
    self.coop ? "Yes" : "No"
  end


  def reset_reviewer_avg_rent
    self.update_column(:reviewer_avg_rent,  array_avg(reviews.rent_included.map(&:monthly_fee)))
  end


  private

  def normalize
    self.address = self.address.downcase.strip
    self.zipcode = self.zipcode.strip
  end

  def array_avg amts
    (amts.inject(0.0) {|sum, fee| sum + fee}/amts.size).round
  rescue
    0
  end

  def rents type=nil
    type.nil? ? reviews.rent_included : reviews.rent_included.send(type.to_s) 
  end

  def reviewer_rent_range
    return "NA" if reviews.rent_included == []
    min, max =  reviews.rent_included.map(&:monthly_fee).minmax
    min == max ? "$#{min.to_i}" : "$#{min.to_i} - $#{max.to_i}"
  end

  def admin_rent_range
    if rent_min && rent_max
      "$#{rent_min} - $#{rent_max}"
    else
      nil
    end
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  before_filter :authenticate_user, :only => [:new, :edit, :update, :create]
  helper_method :sort_column, :sort_direction

  def index
    session[:disable_actions] = nil if params[:reviewer]
    if params[:search]
      if (params[:neighborhood].present? || params[:address].present? || params[:zipcode].present?)
      @buildings = Building.super_search(params).order(sort_column + " " + sort_direction)
      else
      @buildings = Building.search(params[:search]).order(sort_column + " " + sort_direction)
      end
    elsif (params[:neighborhood].present? || params[:address].present? || params[:zipcode].present?)
      @buildings =   Building.locate(params).order(sort_column + " " + sort_direction)
    elsif (params[:sort].present?) 
      @buildings =Building.order(sort_column + " " + sort_direction)
    else 
      @buildings =Building.order(Building::DEFAULT_SORT)
    end
    @buildings = @buildings.page params[:page]
  end

  def show
    @building = Building.find(params[:id])
  end

  def new
    @building = Building.new

  end

  def edit
    @building = Building.find(params[:id])
  end


  def search
    session[:disable_actions] = true
  end

  def create
    @building = Building.new(params[:building])

    if @building.save
      redirect_to new_review_path(:bldg => @building.id)
    else
      render :new
    end
  end

  def update
    @building = Building.find(params[:id])

    if @building.update_attributes(params[:building])
      redirect_to @building, notice: 'building was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    redirect_to buildings_url
  end

  private
  def sort_column
    Building.column_names.include?(params[:sort]) ? params[:sort] : "score"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/views/buildings/_buildings.html.haml
- @buildings.each do |building|
  %li.result.row
    .main-info.span10
      .business
        %h3= link_to building.address, building_path(building)
        = link_to 'Create a review', new_review_path(:bldg =>building), class: "create-review btn btn-mini" unless session[:disable_actions]

      %ul.bldg-stats.row{:data => {"bldg-id" =>"#{building.id}"}, :title=> "Click to visit profile page for: #{building.address}"}><
        %li.img.span2><
          - if building.default_image_id.blank?
            = image_tag 'default-bldg.png'
          - else
            = image_tag BuildingImage.find(building.default_image_id).image.url(:index)
            %br
          %p.rent-range= building.rent_range
        %li.score.span2><
          %b Score:
          %strong><
            =building.score.to_i
            %span.small>< %
        %li.review-cnt.span2><
          = building.reviews.count
          %span.small reviews
        %li.doorman.span2><
          = building.has_doorman
        %li.elevator.span2><
          = building.has_elevator
        %li.avg-rent.span2><
          = "$#{building.reviewer_avg_rent.to_i}"

    %ul.flags.vert-flags.span2
      %li
        .flag.green-flag= building.flags_thrown["Would Recommend"] ? building.flags_thrown["Would Recommend"] : 0
        %span.title Would Recommend
      %li
        .flag.yellow-flag= building.flags_thrown["Neutral"] ? building.flags_thrown["Neutral"] : 0
        %span.title Neutral
      %li
        .flag.red-flag= building.flags_thrown["Not Recommend"] ? building.flags_thrown["Not Recommend"] : 0
        %span.title Would Not Recommend

app/views/buildings/_form.html.haml
= simple_form_for @building do |f|

  .field
    = f.input :address
  .field
    = f.association :neighborhood, :collection => Neighborhood.all(:order => 'name')
  .field
    = f.input :zipcode
  .field
    %ul.inline-list
      %li.inline-field
        = f.input :elevator
      %li.inline-field
        = f.input :doorman
      %li.inline-field
        = f.input :super
      %li.inline-field
        = f.input :coop
  .field
    = f.input :construction_type, :collection => [["Pre-war",1], ["Post-War",2], ["New Construction",3]]

  .actions
    = f.submit :submit, class: "btn btn-primary btn-large"

app/views/buildings/edit.html.haml
%h1 Editing building

= render 'form'

= link_to 'Show', @building
\|
= link_to 'Back', buildings_path

app/views/buildings/index.html.haml
%section.search-results-page

  .container
    %h2.small-heading What building is your apartment in?

    .clearfix

      = form_tag(buildings_path, :method => :get, :id => "buildings_search") do
        .field
          %label{:for => "address"} Filter by address
          %input#search{:name => "search", :type => "text",:id => "search"}

        = hidden_field_tag :neighborhood, params[:neighborhood]
        = hidden_field_tag :zipcode, params[:zipcode]
        = hidden_field_tag :direction, params[:direction]
        = hidden_field_tag :sort, params[:sort]

      %h3.add-listing
        = link_to "Don't see your building? Click here to add it", new_building_path, class: "btn btn-inverse btn-large"

  .sort-list
    .container
      %ul.row
        %li.span2
          %span.sort-item Address
        %li.span2
          %span.sort-item
            %span.arrow
            = sortable "score"
        %li.span2.review-cnt
          %span.sort-item
            %span.arrow
            = sortable "reviews_count","No. Reviews"
        %li.span2.doorman
          %span.sort-item Doorman
        %li.span2.elevator
          %span.sort-item Elevator
        %li.span2.avg-rent
          %span.sort-item
            %span.arrow
            = sortable "reviewer_avg_rent","Rent"
        %li.span2
          %span.sort-item Flags

  .search-results.alt-section

    %ul.container
      - if @buildings.blank?
        %li.no-results No buildings have been added to be reviewed
      - else
        #buildings
          = render "buildings"

    .section-decor
= paginate @buildings

app/views/buildings/index.js.haml
$("#buildings").html("#{escape_javascript(render('buildings')) }");

app/views/buildings/new.html.haml
.container
  %section.new-bldg-page
    .well

      %h2 New building

      = render 'form'

app/views/buildings/search.html.haml
.container
  %section.search-page

    = form_tag(buildings_path, :method => :get) do

      .field
        %label{:for => "neighborhood"} Neighborhood
        = select_tag :neighborhood, options_from_collection_for_select(Neighborhood.all(:order => 'name'), :id, :name), :prompt => "Select your Neighborhood", :id => "neighborhood"

      %span.or or

      .field
        %label{:for => "address"} Address
        %input#address.typeahead{:name => "address", :type => "text", "data-provide" => 'typeahead'}

      %span.or or

      .field
        %label{:for => "zipcode"} Zipcode
        = text_field_tag :zipcode

      = submit_tag 'submit', :class => "btn btn-primary btn-large"

  - content_for :body_end do
    :javascript
      $('.typeahead').typeahead({source: #{Building.all.map(&:address)}});

app/views/buildings/show.html.haml
%section.bldg-page
  .container
    %p#notice= notice

    .bldg-overview

      .row
        .span6.offset1
          %h2.address= @building.address

          .row
            #myCarousel.carousel.span3
              .carousel-inner
                .active.item
                  - if @building.default_image_id.blank?
                    = image_tag 'default-bldg.png'
                  - else
                    = image_tag BuildingImage.find(@building.default_image_id).image.url(:small)
                - @building.reviews.each do |review|
                  - review.building_images.each do |img|
                    .item
                      = image_tag img.image.url(:small)

              - unless @building.building_images.blank?
                %a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} ‹
                %a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} ›

            .score.span3
              %b Score:
              %strong><
                = @building.score.to_i
                %span.small>< %

        .span5
          %ul.bldg-features
            %li
              %span Doorman:
              = @building.has_doorman
            %li
              %span Elevator:
              = @building.has_elevator
            %li
              %span Super:
              = @building.has_super
            %li
              %span Co-Op:
              = @building.is_coop
            %li
              %span Construction:
              = @building.construction
            %li
              %span Apts:
              - @building.apt_types.each do |k,v|
                = "#{k} "
            %li
              %span Average Age:
              = @building.reviewer_average_age.to_i
            %li
              %span Average Occupancy:
              = @building.average_years_lived
            %li
              %span Rent Range:
              = @building.rent_range
            %li
              %span Average Rent:
              = "$#{@building.avg_rent.to_i}"

      .row
        .span12
          %ul.big-flags
            %li
              %b.large-flag.green-flag
                = @building.flags_thrown["Would Recommend"] ? @building.flags_thrown["Would Recommend"] : 0
              %span.big-link Would recommend
            %li
              %b.large-flag.yellow-flag
                = @building.flags_thrown["Neutral"] ? @building.flags_thrown["Neutral"] : 0
              %span.big-link Neutral
            %li
              %b.large-flag.red-flag
                = @building.flags_thrown["Not Recommend"] ? @building.flags_thrown["Not Recommend"] : 0
              %span.big-link Would not recommend


  .alt-section
    .section-decor
    .container

      .bldg-reviews
        .row
          .span10.offset1
            - ReviewMetadata.all_fields.each do |f|
              -pct = @building.send("#{f}_avg".to_sym)
              .row
                .progress-title.span3
                  %strong= f.titleize
                .span5
                  #progressbar
                    .inner{:style =>"width:#{pct}%"}
                .progress-num.span2
                  %strong= (pct/20).round(1)

      .bldg-comments
        %h3 Comments
        %ul
          - @building.reviews.each do |review|
            - unless review.comment.blank?
              %li
                "#{link_to review.comment, review_path(review)}"

    .section-decor