config/routes.rb
Homerefs::Application.routes.draw do
  # get "errors/error_404"
  # get "errors/error_500"

  resources :feedbacks

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'public#landing'

  resources :reviews, :only => [:new, :show, :edit, :create, :update ]

  resources :apartments

  resources :buildings

  resources :users

  resources :identities

  match '/home', to: 'reviews#home'
  match '/about', to: 'public#about_us'
  match '/how-it-works', to: 'public#how_it_works'
  match '/faq', to: 'public#faq'
  match '/terms', to: 'public#terms'
  match '/contact', to: 'public#contact'
  match '/auth/:provider/callback', to: 'sessions#create'
  match "/auth/failure", to: "sessions#failure"
  match '/login', to: 'sessions#new', as: 'login'
  match '/logout', to: 'sessions#destroy', as: 'logout'
  match '/search', to: 'buildings#search'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  belongs_to :user
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates :user_id, :presence => true


end

app/controllers/identities_controller.rb
class IdentitiesController < ApplicationController

  def new
    @identity = env['omniauth.identity']
  end

end

app/views/identities/new.html.haml
.container
  %section.new-user
    .well

      %h2 Create an account

      = form_tag users_path do
        - if @identity && @identity.errors.any?
          .error_messages
            %h2
              = pluralize(@identity.errors.count, "error")
              prohibited this account from being saved:
            %ul
              - @identity.errors.full_messages.each do |msg|
                %li= msg
              - @user.errors.full_messages.each do |msg|
                %li= msg
        .field
          = label_tag :name
          = text_field_tag :name, @identity.try(:name)
        .field
          = label_tag :email
          = email_field_tag :email, @identity.try(:email)
        .field
          = label_tag :password
          = password_field_tag :password
        .field
          = label_tag :password_confirmation
          = password_field_tag :password_confirmation

        = render :partial => 'shared/dob_and_gender'

        .actions
          = submit_tag "Register", class: "btn btn-primary btn-large"