config/routes.rb
Homerefs::Application.routes.draw do
  # get "errors/error_404"
  # get "errors/error_500"

  resources :feedbacks

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'public#landing'

  resources :reviews, :only => [:new, :show, :edit, :create, :update ]

  resources :apartments

  resources :buildings

  resources :users

  resources :identities

  match '/home', to: 'reviews#home'
  match '/about', to: 'public#about_us'
  match '/how-it-works', to: 'public#how_it_works'
  match '/faq', to: 'public#faq'
  match '/terms', to: 'public#terms'
  match '/contact', to: 'public#contact'
  match '/auth/:provider/callback', to: 'sessions#create'
  match "/auth/failure", to: "sessions#failure"
  match '/login', to: 'sessions#new', as: 'login'
  match '/logout', to: 'sessions#destroy', as: 'logout'
  match '/search', to: 'buildings#search'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user, :except => [:show, :index]
  before_filter :set_metadata, :only => [:new, :edit, :create]

  def home

  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    # @review = Review.new
    @building = Building.find(params[:bldg])
    @review = @building.reviews.build
  end

  def edit
    @review = Review.find(params[:id])
    @building = @review.building
  end

  def create
    @review = current_user.reviews.build(params[:review])
    if @review.save
      save_images
      redirect_to @review, notice: 'Review was successfully created.'
    else
      @building = @review.building
      render action: "new"
    end
  end

  def update

    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        @review.calc_score
        save_images
        format.html {redirect_to @review, notice: 'Review was successfully updated.'}
        format.json { render :json => @review}
      else
        format.html {render action: "edit"}
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to reviews_path
  end

  private

  def save_images
    #TODO is there a better way to save these images at review create/update
    #time?
    1.upto(3).each do |i|
      if params["review"]["image#{i}"]
        @review.building_images.create(building_id: @review.building_id, image: params["review"]["image#{i}"])
      end
    end
  end

  def set_metadata
    @rows = ReviewMetadata.order("position asc")
    @hilows ={}
    @rows.each do |row|
      @hilows[row.field_name] = {"hi" => row.hi_text, "low" => row.low_text}
    end
  end
end

app/views/reviews/_form.html.erb
<%= simple_form_for @review , :html => {:id => "review_form", :data => {:allFields => ReviewMetadata.all_fields} } do |f| %>
  <% @review.values.each do |k,v| %>
    <%= f.input k.to_sym, :as => :hidden, :input_html => {:id => "_#{k}", :value => v} %>
  <% end %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:" %>
      </h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :building_id, :as => :hidden, :input_html => {:value => @building.id} %>
  <div class="field">
    <div class="row">
      <div class="span3 offset2">
        <%= f.input :apt_size, :collection => Review::APT_SIZE.map{|k,v| [v,k]} %>
      </div>
      <div class="span3">
        <%= f.input :years_lived %>
      </div>
      <div class="span3">
        <%= f.input :monthly_fee, :label => "Rent / Maintenance", :input_html => {:step => 25, :min => 250 } %>
      </div>
    </div>
  </div>
  <div class="field">
    <%= f.input :comment %>
  </div>
  <div class="field images">
    <%= f.input :image1, :as => :file, :label => "Image 1" %>
    <%= f.input :image2, :as => :file, :label => "Image 2" %>
    <%= f.input :image3, :as => :file, :label => "Image 3" %>
  </div>
  <div class="field">
    <%= f.input :assessment, :collection => Review::FLAGS.map{|k,v| [v,k]}, :as => :radio_buttons, :label => "Flags" %>
  </div>
  <div class="actions">
    <%= f.submit :submit, class: "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/reviews/_form_wrapper.html.erb
<div class="container">
  <section class="new-review-page centered-form">
    <h2 class="small-heading">
      <%= "#{controller.action_name.capitalize} Review for" %>
      <span class="address">
        <%= @building.address %>
      </span>
    </h2>
    <ul class="bldg-info inline-list">
      <li>
        <span>Doorman:</span>
        <%= @building.has_doorman %>
      </li>
      <li>
        <span>Elevator:</span>
        <%= @building.has_elevator %>
      </li>
      <li>
        <span>Live in Super:</span>
        <%= @building.has_super %>
      </li>
      <li>
        <span>Co-Op:</span>
        <%= @building.is_coop %>
      </li>
    </ul>
    <%= render :partial => 'slider', :locals => {:hilows => @hilows} %>
    <%= render :partial => 'form' %>
  </section>
</div>

app/views/reviews/_slider.html.erb
<div class="slider_panel">
  <% @rows.each_with_index do |row, index| %>
    <% field = row.field_name %>
    <div class="slider-group">
      <p class="slider-label left">
        <%= hilows[field]["low"] %>
      </p>
      <div class="slider-main">
        <p class="title">
          <%= field.titleize %>
        </p>
        <% if index == 0 %>
          <div class="slider-scale clearfix">
            <span class="first">
              1
              <b>
                |
              </b>
            </span>
            <span class="second">
              2
              <b>
                |
              </b>
            </span>
            <span class="third">
              3
              <b>
                |
              </b>
            </span>
            <span class="fourth">
              4
              <b>
                |
              </b>
            </span>
            <span class="last">
              5
              <b>
                |
              </b>
            </span>
          </div>
        <% end %>
        <div class="slider-bar" id="<%= field %>"></div>
      </div>
      <p class="slider-label right">
        <%= hilows[field]["hi"] %>
      </p>
    </div>
  <% end %>
</div>

app/views/reviews/edit.html.haml
= render :partial => "form_wrapper"

app/views/reviews/home.html.haml
%h1
  = link_to "Review an Apartment", buildings_path
%h1
  = link_to "Search for an Apartment", search_path

app/views/reviews/new.html.haml
= render :partial => "form_wrapper"

app/views/reviews/show.html.erb
<section class="bldg-page review-page">
  <div class="container">
    <div class="review-info">
      <h3>Thanks for submitting your review! The average scores are below</h3>
      <p>
        Your rating for
        <em></em>
        <%= link_to @review.building.address, @review.building %>
        is:
        <strong><%=@review.score.to_i%>%</strong>
      </p>
      <% if @review.building_images %>
        <ul class="inline-list"></ul>
        <% @review.building_images.each do |img| %>
          <% unless img.image.url.split("/")[-1] == "missing.png" %>
            <li class="img">
              <%= image_tag img.image.url(:small) %>
            </li>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="alt-section">
    <div class="section-decor"></div>
    <div class="container">
      <div class="row">
        <div class="bldg-reviews span10 offset1">
          <% ReviewMetadata.all_fields.each do |f| %>
            <% pct = @review.send(f.to_sym) * 20 %>
            <div class="row">
              <div class="progress-title span3">
                <strong>
                  <%= f.titleize %>
                </strong>
              </div>
              <div class="span5">
                <div id="progressbar">
                  <div class="inner" style="width:<%= pct %>%"></div>
                </div>
              </div>
              <div class="progress-num span2">
                <strong>
                  <%= (pct/20).to_i %>
                </strong>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="bldg-comments">
        <% unless @review.comment.empty? %>
          <h3>
            Comment
          </h3>
          <p><%=@review.comment%></p>
        <% end %>
      </div>
    </div>
    <div class="section-decor"></div>
  </div>
</section>
      