config/routes.rb
Homerefs::Application.routes.draw do
  # get "errors/error_404"
  # get "errors/error_500"

  resources :feedbacks

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'public#landing'

  resources :reviews, :only => [:new, :show, :edit, :create, :update ]

  resources :apartments

  resources :buildings

  resources :users

  resources :identities

  match '/home', to: 'reviews#home'
  match '/about', to: 'public#about_us'
  match '/how-it-works', to: 'public#how_it_works'
  match '/faq', to: 'public#faq'
  match '/terms', to: 'public#terms'
  match '/contact', to: 'public#contact'
  match '/auth/:provider/callback', to: 'sessions#create'
  match "/auth/failure", to: "sessions#failure"
  match '/login', to: 'sessions#new', as: 'login'
  match '/logout', to: 'sessions#destroy', as: 'logout'
  match '/search', to: 'buildings#search'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta/>
    <title>
      <%= content_for?(:title) ? yield(:title) : "HomeRefs" %>
    </title>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!--[if lt IE 9]
      <script>(src="http://html5shiv.googlecode.com/svn/trunk/html5.js")</script>
    -->
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png"></link>
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png"></link>
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png"></link>
  </head>
  <body>
    <header class="container clearfix" role="banner">
      <h1>
        <%= link_to "HomeRefs", :root, class: "brand" %>
      </h1>
      <nav role="navigation">
        <ul class="nav-list">
          <li class="nav-item">
            <%= link_to "How It Works", '/how-it-works' %>
          </li>
          <li class="nav-item">
            <%= link_to "About",'/about' %>
          </li>
          <li class="nav-item">
            <%= link_to "FAQ",'/faq' %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path %>
          </li>
          <% if user_logged_in? %>
            <li class="nav-item main-link">
              <ul>
                <li class="dropdown" id="menu1">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
                    My Account
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "History", user_path(current_user.id) %>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Log Out", logout_path %>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item main-link">
              <%= link_to "Log In", login_path %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg.html_safe, :class =>"#{name}", :id => "flash_#{name}" %>
      <% end %>
    </div>
    <%= yield %>
    <div class="container">
      <footer role="contentinfo">
        <p>
          HomeRefs Copyright &copy; 2012. All Rights Reserved.
          <%= link_to "| Feedback ", new_feedback_path, class: "main-link" %>
          <%= link_to "| Terms ", terms_path, class: "main-link" %>
        </p>
      </footer>
    </div>
    <%= javascript_include_tag "application", "core" %>
    <%= yield :body_end %>
  </body>
</html>